version: 2

defaults: &defaults
  docker:
    - image: angular/ngcontainer:latest@sha256:46eeaef4b4918682e0163a2ec79cb11922688354034f372285b6bf62bf63f786
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum  "yarn.lock" }}
      - run: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a yarn test
      - store_artifacts:
          path: ~/repo/dist
          destination: dist
